### ISSUE TITLE
SQL import Foreign Key problem

### ISSUE THREAD

**Issue by dalliard** [dannyvankooten/ana#3]
In the sql import file you alter the table ``pageviews`` and reference to the ``pages`` table before it is created, that will result in an error during the import. Create the table ``pages`` first, then alter ``pageviews``.

**Comment by dannyvankooten** [comment]
Hey @dalliard,

So awesome to see that you're already spinning up an Ana instance. I feel obliged to say that you will most likely run into more issues like these as it's all in a very early stage right now and I'd hate for you to waste your time. I expect things to stabilise in a few more months.

That said, thanks a ton for the heads up. Should be fixed in 0289ba8cfedb50205a436f963f12529cce90605a. 

Have a good Christmas!
